### ISSUE TITLE
How to build with Scala 2.12?

### ISSUE THREAD

**Issue by irvinktang** [Azure/azure-event-hubs-spark#528]
I'm currently trying to build this package with Scala 2.12 and not 2.11. It's my first time working with a POM so I wasn't sure how to proceed. 

The reason why I'm trying to build the package with this Scala version is because we're currently using the connector in our Databricks cluster running Databricks Runtime 7.0 + Spark 3.0. The runtime uses Scala 2.12. We were having some issues with the connector and it seems to be compatibility issues with Spark 3.0. There was currently a fix made in PR [#520](https://github.com/Azure/azure-event-hubs-spark/pull/520) that would resolve the error, but it won't be out until the next release. 

I tried just changing the Scala version from 2.11 to 2.12 and Spark version from 2.3.3 to 3.0.0 but that gave me the following errors:
`object SharedSQLContext is not a member of package org.apache.spark.sql.test`
The other errors were similar, stating how certain objects were not members of certain packages.

**Comment by nyaghma** [comment]
@irvinktang Try building the package with Scala 2.12 and Spark 2.4.5 and use the generated package in your environment with Spark 3.0.

**Comment by irvinktang** [comment]
@nyaghma I was able to build the package successfully. However, when uploading and installing onto my environment, received this error:
`org.apache.spark.eventhubs.EventHubsUtils.encrypt does not exist in the JVM`
on this line:
`ehConf['eventhubs.connectionString'] = sc._jvm.org.apache.spark.eventhubs.EventHubsUtils.encrypt(connectionStringStaging)`

It was my understanding from the [docs](https://github.com/Azure/azure-event-hubs-spark/blob/master/docs/PySpark/structured-streaming-pyspark.md#event-hubs-configuration) that I needed to encrypt the connection string. 

Once I went back to simply building the ehConf dictionary with the key and non-encrypted connection string, got this error:
`StreamingQueryException: com/microsoft/azure/eventhubs/EventHubClientOptions`

**Comment by irvinktang** [comment]
I recloned the repository, and only changed the Scala and Spark versions in `pom.xml` on lines 52 and 53. Was able to build successfully. This time, I get a different error after uploading (at the same place):
`StreamingQueryException: Could not initialize class org.apache.spark.eventhubs.package$`

**Comment by nyaghma** [comment]
@irvinktang Have you added azure-eventhubs 3.2.0 and scala-java8-compat libraries to your cluster?

**Comment by irvinktang** [comment]
@nyaghma Just added those. For the scala-java8-compat library, I used version 0.9.0. However, still getting the same error as before. The connector has worked in the past without these libraries in the cluster as far as I know (I didn't see any explicit libraries listed)

**Comment by nyaghma** [comment]
If you are using the PySpark you need to encrypt the connection string. The encrypt exists in azure-eventhubs 3.2.0. Right now I'm confused if you are seeing the error with encrypted or non-encrypted connection string. 
I'm trying to repro the issue using the same set-up but haven't been able to do so.

**Comment by irvinktang** [comment]
So I tried running the notebook once with the encrypted connection string and once with the non-encrypted connection string. I get the error both times. I also just restarted the cluster and re-ran the notebook with the encrypted connection string but the job hangs.  
I still have azure-eventhubs 3.2.0 and the scala-java8-compat library installed on this cluster.

**Comment by nyaghma** [comment]
@irvinktang After restarting with the encrypted connection string you don't see the "encrypt does not exist in the JVM" error, am I right?  Does the job hang silently or there is an error? Do you see the same issue in an environment using Spark 2.4?

**Comment by irvinktang** [comment]
Yes, correct. It hangs silently, no error is thrown in the notebook. Tried running it on a different cluster running Spark 2.4, but I think there's a separate, non-related issue as the commands attached to that cluster hang and then end up getting cancelled

**Comment by irvinktang** [comment]
@nyaghma it also is silently hanging when running on a cluster using Spark 2.4

**Comment by nyaghma** [comment]
Ok, then we need to look into the code and stack trace to find out what causes the issue. I'd be happy to help if you can share those with me.

**Comment by irvinktang** [comment]
@nyaghma I'm posting a modified version of our code. I've labeled where I've modified the code. 
```
table_name = "sometable"

attributes = attributes_env[table_name]
    
db_table_name = "database." + table_name

table_location = "/mnt/delta_loc/" + table_name

checkpoint_location = "/mnt/delta_loc/_checkpoints/" + table_name

ehConf = {
#   'eventhubs.connectionString': connectionStringStaging
}

ehConf['eventhubs.connectionString'] = sc._jvm.org.apache.spark.eventhubs.EventHubsUtils.encrypt(connectionStringStaging)
  
# add columns where needed for attributes in map to table
attributesFields = []
attributesSchemaList = []
cols = spark.sql("SHOW COLUMNS FROM {}".format(db_table_name)).rdd.flatMap(lambda x: x).collect()

for key, value in attributes.items():
     attributesFields.append(StructField(key, get_attribute_type(value), True))
     attributesSchemaList.append("attributes_struct.{}".format(key))
     if not key in cols:
          spark.sql("ALTER TABLE {} ADD COLUMNS ({} {})".format(db_table_name, key, value))
attributesSchema = StructType(attributesFields)

def upsertToDelta(microBatchOutputDF, batchId): 
  microBatchOutputDF.dropDuplicates(subset=['id']).createOrReplaceTempView("updates")
  microBatchOutputDF._jdf.sparkSession().sql("""
    MERGE INTO {} t
    USING updates s
    ON (s.partition = t.partition) and (s.id = t.id)
    WHEN MATCHED THEN UPDATE SET *
    WHEN NOT MATCHED THEN INSERT *
  """.format(db_table_name))

# ======================== modified code to share publicly ==============================
Schema = StructType([StructField("time", TimestampType()),
                      StructField("msg", StructType( 
                          [StructField("some_attr", StringType(), True),
                           StructField("some_id", StringType())]))
                    ])
    
df = spark.readStream.format("eventhubs").options(**ehConf).load()

df = df.selectExpr("cast(body as string) as json").\
                   select(from_json("json", Schema).alias("data")).\
                   withColumn("id", coalesce("data.msg.some_id", gen_uuid())).\
# ========================================================================================

# partitionBy isn't needed here since table is already partitioned
df.writeStream.format("delta").foreachBatch(upsertToDelta).outputMode("update").\
  option("checkpointLocation",checkpoint_location).\
  start(table_location).\
  awaitTermination()
```
Had a hard time pinpointing the location in the logs specific to this. I tried matching the times shown in the logs with the time I ran the notebook.

Logj4 output:
```
20/08/05 21:27:15 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:15 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:15 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:15 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:15 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:15 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:15 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:15 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:15 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:15 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:15 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:15 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:15 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:15 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:15 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:15 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:15 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:15 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:15 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:15 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:15 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:15 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:15 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:15 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:15 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:16 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:16 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:16 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:16 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:16 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:16 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:16 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:16 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:16 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:16 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:16 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:16 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:16 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:16 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:16 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:16 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:16 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:16 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:16 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:16 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:16 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:16 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:16 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
20/08/05 21:27:16 INFO EventHubsSource: GetOffset: Vector(({"ehName":"testpythonscript","partitionId":0},824594), ({"ehName":"testpythonscript","partitionId":1},11188))
```
Standard output:
```
2020-08-05T21:26:28.213+0000: [GC (Allocation Failure) [PSYoungGen: 10003523K->2932680K(9004544K)] 19193532K->12122689K(40401920K), 0.6916372 secs] [Times: user=1.13 sys=0.03, real=0.68 secs] 
2020-08-05T21:27:02.942+0000: [GC (Allocation Failure) [PSYoungGen: 9004488K->3448939K(10234368K)] 18194497K->12639618K(41631744K), 0.6576301 secs] [Times: user=1.30 sys=0.01, real=0.66 secs] 
2020-08-05T21:30:17.153+0000: [GC (System.gc()) [PSYoungGen: 5645333K->2253212K(10465792K)] 14836012K->11444378K(41863168K), 0.4312887 secs] [Times: user=0.93 sys=0.00, real=0.43 secs] 
2020-08-05T21:30:17.585+0000: [Full GC (System.gc()) [PSYoungGen: 2253212K->0K(10465792K)] [ParOldGen: 9191166K->3633522K(31397376K)] 11444378K->3633522K(41863168K), [Metaspace: 284287K->282167K(309248K)], 4.6685828 secs] [Times: user=5.61 sys=0.08, real=4.68 secs] 
```

**Comment by irvinktang** [comment]
@nyaghma hey it turns out, that job was actually supposed to hang. So everything works now! Thanks for all your help :)
